name: Extract and Filter Links

on:
  schedule:
    - cron: '0 0 * * 4'
  workflow_dispatch:

jobs:
  extract-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: Automation

      - name: Create Outputs Directory
        run: mkdir -p .github/outputs

      - name: Check if README.md exists
        run: |
          if [ -f README.md ]; then
            sed -n -e 's!.*\(http[s]\?://[^<]*\).*!\1!p' README.md \
            | grep -Ev 'reddit\.com|apkmirror\.com|docs\.google\.com|1drv\.ms|m3\.material\.io|en\.wikipedia\.org|pling\.com|github\.com/TeaOwO/Material-You-Apps/assets|m3-markdown-badges\.vercel\.app|android\.stackexchange\.com|coolapk\.com|github\.com/TeaEndsAcronyms/Material-You-Apps/assets|apkmonk\.com' \
            | sed 's/[()]//g' \
            | sed 's/ðŸ´Fork/`\\0`/g' \
            | sed 's/[<>]//g' > .github/outputs/filtered-links.txt
          else
            echo "README.md not found."
            exit 1  # Exit with an error code
          fi

      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Commit Changes
        run: |
          git add .github/outputs/filtered-links.txt
          git commit -m "Update Filtered Links"
          git push origin HEAD
